prompts = [
    "In the future, artificial intelligence will",
    "Scientists have discovered a new way to",
    "On a distant planet, aliens are",
    "One of the greatest inventions in human history is",
    "In a peaceful village, the residents daily",
    "In a mysterious forest, explorers found",
    "In a bustling city, people are",
    "In an ancient castle, there is a hidden",
    "In a future society, robots will",
    "In a magical world, wizards can",
    "On a remote island, the expedition team discovered",
    "In a peaceful country, people enjoy",
    "In a challenging environment, warriors must",
    "In a technologically advanced future, people can",
    "In a place full of wonders, children can",
    "In an ancient legend, heroes must",
    "On an adventurous journey, explorers will",
    "In a mysterious cave, archaeologists found",
    "In a future city, transportation will",
    "In a world full of hope, people can",
    "In the heart of a bustling market, traders exchange",
    "At the edge of a vast desert, an ancient artifact lies",
    "Within the depths of the ocean, a sunken city holds",
    "Through the pages of an old book, secrets of the past",
    "On the highest mountain peak, a rare flower blooms",
    "In a world where dreams come to life, dreamers can",
    "In a laboratory filled with cutting-edge equipment, scientists create",
    "In a land where music is the language, musicians communicate",
    "Under the light of a full moon, creatures of myth gather",
    "In a society that values harmony above all, citizens strive",
    "Amidst the ruins of a forgotten civilization, historians uncover",
    "In a universe where time travel is possible, adventurers journey",
]
